choice = "1"
secret = "42"
identity_secret = "123"
poll_id = "0"

commitment = "10768868654894799257910424228206332091878549504228410743539346844038381518440"
nullifier = "18864455324415923350837963873555520089825199659156710189515894249203574371945"
membership_root = "479653171209926143526691675219993872726743078529227032620836821713077361170"

# All-zero path (depth 20)
path_bits = ["0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"]
path_siblings = ["0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"]
